name: portfolio
description: "Thant Zin's Portfolio"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.2
  shared_preferences: ^2.5.3
  provider: ^6.1.5
  firebase_core: ^4.1.0
  firebase_analytics: ^12.0.0
  visibility_detector: ^0.4.0+2
  intl: any
  font_awesome_flutter: ^10.10.0
  flutter_svg: ^2.2.1
  cloud_firestore: ^6.0.1
  equatable: ^2.0.7
  logger: ^2.6.1
  flutter_spinkit: ^5.2.2
  flutter_native_splash: ^2.4.6
  go_router: ^16.2.1
  layout: ^1.0.5
  google_fonts: ^6.3.1
  liquid_progress_indicator_v2: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mocktail: ^1.0.4
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/splash.png
  color_dark: "#000000"
  image_dark: assets/splash.png

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/portfolios/

  fonts:
    - family: BungeeSpice
      fonts:
        - asset: assets/fonts/BungeeSpice-Regular.ttf
