// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4TK4PYa2mKD5RRL97T2uUo_tP8hNsRQU',
    appId: '1:1071941194582:web:826a2c8a2c9bc4b65bfcf7',
    messagingSenderId: '1071941194582',
    projectId: 'thantzin-portfolio',
    authDomain: 'thantzin-portfolio.firebaseapp.com',
    storageBucket: 'thantzin-portfolio.firebasestorage.app',
    measurementId: 'G-QCT12515WH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPgE2Eiub0zgy558ObH44fZELj7dcyBjE',
    appId: '1:1071941194582:android:95328f01fdcf21a15bfcf7',
    messagingSenderId: '1071941194582',
    projectId: 'thantzin-portfolio',
    storageBucket: 'thantzin-portfolio.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAr0qKDTxctqub8dBbr-PCvQCXpv-iZJLc',
    appId: '1:1071941194582:ios:c6209236b937b7145bfcf7',
    messagingSenderId: '1071941194582',
    projectId: 'thantzin-portfolio',
    storageBucket: 'thantzin-portfolio.firebasestorage.app',
    iosBundleId: 'com.example.portfolio',
  );
}
