// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4TK4PYa2mKD5RRL97T2uUo_tP8hNsRQU',
    appId: '1:1071941194582:web:826a2c8a2c9bc4b65bfcf7',
    messagingSenderId: '1071941194582',
    projectId: 'thantzin-portfolios',
    authDomain: 'thantzin-portfolios.firebaseapp.com',
    storageBucket: 'thantzin-portfolios.firebasestorage.app',
    measurementId: 'G-QCT12515WH',
  );
}
